using System.Security.Cryptography;
using System.Text;
using Microsoft.Extensions.Configuration;

namespace NickERP.Platform.Identity.Database.Services;

/// <summary>
/// Sprint 21 / Phase B — pure crypto for hashing one-time invite
/// tokens. Same shape as
/// <c>NickERP.Platform.Audit.Database.EdgeKeyHasher</c> (Sprint 13);
/// kept distinct so an invite-token hash never collides with an
/// edge-API-key hash even if the same plaintext is somehow
/// generated twice.
/// </summary>
/// <remarks>
/// <para>
/// <b>Hash construction.</b> Plaintext token bytes are HMAC-SHA256
/// under a server-side hash key. The key is read from
/// <c>InviteTokens:HashKey</c> config; if missing the hasher falls
/// back to a deterministic-per-host value derived through
/// <see cref="IInviteTokenHashEnvelope"/> (production wiring backs
/// it with <c>IDataProtectionProvider</c>; tests inject a constant).
/// </para>
/// <para>
/// <b>Plaintext storage.</b> The plaintext token is generated once,
/// surfaced in the email body, and discarded server-side. Only the
/// HMAC hash + an 8-char non-secret prefix are persisted.
/// </para>
/// </remarks>
public sealed class InviteTokenHasher
{
    /// <summary>Configuration key for the explicit server-side hash key.</summary>
    public const string HashKeyConfigKey = "InviteTokens:HashKey";

    /// <summary>Length (bytes) of CSPRNG plaintext tokens generated by <see cref="GenerateToken"/>. 24 bytes => 32 url-safe base64 chars.</summary>
    public const int TokenMaterialLengthBytes = 24;

    /// <summary>Number of leading characters of the plaintext token surfaced as <see cref="Entities.InviteToken.TokenPrefix"/>.</summary>
    public const int TokenPrefixLength = 8;

    private readonly IConfiguration _config;
    private readonly IInviteTokenHashEnvelope _envelope;

    public InviteTokenHasher(IConfiguration config, IInviteTokenHashEnvelope envelope)
    {
        _config = config ?? throw new ArgumentNullException(nameof(config));
        _envelope = envelope ?? throw new ArgumentNullException(nameof(envelope));
    }

    /// <summary>
    /// HMAC-SHA256 the plaintext under the server's hash key. The
    /// caller compares the returned bytes against
    /// <see cref="NickERP.Platform.Identity.Entities.InviteToken.TokenHash"/>
    /// via <c>FixedTimeEquals</c> (the unique index handles the
    /// lookup; the FTE is defence-in-depth).
    /// </summary>
    public byte[] ComputeHash(string plaintextToken)
    {
        ArgumentException.ThrowIfNullOrEmpty(plaintextToken);
        var serverHashKey = ResolveServerHashKey();
        try
        {
            using var hmac = new HMACSHA256(serverHashKey);
            return hmac.ComputeHash(Encoding.UTF8.GetBytes(plaintextToken));
        }
        finally
        {
            CryptographicOperations.ZeroMemory(serverHashKey);
        }
    }

    /// <summary>
    /// Generate a fresh CSPRNG plaintext invite token. URL-safe
    /// base64 (no padding) — the token slots straight into the
    /// invite-link path segment without escaping.
    /// </summary>
    public static string GenerateToken()
    {
        var bytes = new byte[TokenMaterialLengthBytes];
        RandomNumberGenerator.Fill(bytes);
        return Convert.ToBase64String(bytes)
            .TrimEnd('=')
            .Replace('+', '-')
            .Replace('/', '_');
    }

    /// <summary>Compute the operator-visible 8-char prefix.</summary>
    public static string ComputePrefix(string plaintextToken)
    {
        ArgumentException.ThrowIfNullOrEmpty(plaintextToken);
        return plaintextToken.Length <= TokenPrefixLength
            ? plaintextToken
            : plaintextToken[..TokenPrefixLength];
    }

    private byte[] ResolveServerHashKey()
    {
        var configured = _config[HashKeyConfigKey];
        if (!string.IsNullOrEmpty(configured))
        {
            return Encoding.UTF8.GetBytes(configured);
        }
        return _envelope.DeriveFallbackHashKey();
    }
}

/// <summary>
/// Host-supplied envelope for deriving the fallback HMAC hash key
/// when <c>InviteTokens:HashKey</c> is unset. Hosts inject an
/// implementation backed by <c>IDataProtectionProvider</c>; tests
/// inject a deterministic constant. Mirrors the
/// <c>IEdgeKeyHashEnvelope</c> pattern (Sprint 13).
/// </summary>
public interface IInviteTokenHashEnvelope
{
    /// <summary>
    /// Return a stable, host-scoped 32-byte hash key. Call sites
    /// must ensure the value is consistent across the host's
    /// lifetime — rotating the underlying secret would invalidate
    /// every issued invite.
    /// </summary>
    byte[] DeriveFallbackHashKey();
}
