// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NickERP.Platform.Audit.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NickERP.Platform.Audit.Database.Migrations
{
    [DbContext(typeof(AuditDbContext))]
    [Migration("20260429061910_AddSystemContextOptInToEvents")]
    partial class AddSystemContextOptInToEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("audit")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NickERP.Platform.Audit.Database.DomainEventRow", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<JsonDocument>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("PrevEventHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long?>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("EventId");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_audit_events_correlation");

                    b.HasIndex("EventType", "OccurredAt")
                        .HasDatabaseName("ix_audit_events_system_type_time")
                        .HasFilter("\"TenantId\" IS NULL");

                    b.HasIndex("TenantId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_audit_events_tenant_idempotency");

                    b.HasIndex("TenantId", "ActorUserId", "OccurredAt")
                        .HasDatabaseName("ix_audit_events_actor_time");

                    b.HasIndex("TenantId", "EventType", "OccurredAt")
                        .HasDatabaseName("ix_audit_events_type_time");

                    b.HasIndex("TenantId", "EntityType", "EntityId", "OccurredAt")
                        .HasDatabaseName("ix_audit_events_entity_time");

                    b.ToTable("events", "audit");
                });
#pragma warning restore 612, 618
        }
    }
}
