// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NickERP.EdgeNode;

#nullable disable

namespace NickERP.EdgeNode.Migrations
{
    [DbContext(typeof(EdgeBufferDbContext))]
    partial class EdgeBufferDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("NickERP.EdgeNode.EdgeOutboxEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EdgeNodeId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("EdgeTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventPayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventTypeHint")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastReplayError")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ReplayAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset?>("ReplayedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("TenantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_edge_outbox_pending")
                        .HasFilter("\"ReplayedAt\" IS NULL");

                    b.ToTable("edge_outbox", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
