// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NickERP.NickFinance.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NickERP.NickFinance.Database.Migrations
{
    [DbContext(typeof(NickFinanceDbContext))]
    [Migration("20260429131827_Init_NickFinance")]
    partial class Init_NickFinance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("nickfinance")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NickERP.NickFinance.Core.Entities.FxRate", b =>
                {
                    b.Property<string>("FromCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("ToCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("PublishedByUserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Rate")
                        .HasColumnType("numeric(18,8)");

                    b.Property<long?>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("FromCurrency", "ToCurrency", "EffectiveDate");

                    b.HasIndex("FromCurrency", "ToCurrency", "EffectiveDate")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_fx_rate_pair_effective_desc");

                    b.ToTable("fx_rate", "nickfinance", t =>
                        {
                            t.HasCheckConstraint("ck_fx_rate_positive", "\"Rate\" > 0");
                        });
                });

            modelBuilder.Entity("NickERP.NickFinance.Core.Entities.LedgerEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("AmountBase")
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("AmountNative")
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("BoxId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CorrectsEventId")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrencyBase")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("CurrencyNative")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<decimal>("FxRate")
                        .HasColumnType("numeric(18,8)");

                    b.Property<DateTime>("FxRateDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("PostedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PostedByUserId")
                        .HasColumnType("uuid");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("VoucherId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CorrectsEventId")
                        .HasDatabaseName("ix_ledger_corrects");

                    b.HasIndex("VoucherId")
                        .HasDatabaseName("ix_ledger_voucher");

                    b.HasIndex("TenantId", "BoxId", "PostedAt")
                        .HasDatabaseName("ix_ledger_tenant_box_posted");

                    b.ToTable("petty_cash_ledger_events", "nickfinance", t =>
                        {
                            t.HasCheckConstraint("ck_ledger_amount_base_nonneg", "\"AmountBase\" >= 0");

                            t.HasCheckConstraint("ck_ledger_amount_native_nonneg", "\"AmountNative\" >= 0");
                        });
                });

            modelBuilder.Entity("NickERP.NickFinance.Core.Entities.PettyCashBox", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApproverUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<Guid>("CustodianUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("OpeningBalanceAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,4)")
                        .HasDefaultValue(0m);

                    b.Property<string>("OpeningBalanceCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_petty_cash_boxes_tenant");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_petty_cash_boxes_tenant_code");

                    b.ToTable("petty_cash_boxes", "nickfinance", t =>
                        {
                            t.HasCheckConstraint("ck_petty_cash_boxes_custodian_neq_approver", "\"CustodianUserId\" <> \"ApproverUserId\"");

                            t.HasCheckConstraint("ck_petty_cash_boxes_opening_currency_match", "\"OpeningBalanceCurrency\" = \"CurrencyCode\"");
                        });
                });

            modelBuilder.Entity("NickERP.NickFinance.Core.Entities.PettyCashPeriod", b =>
                {
                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<string>("PeriodYearMonth")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ClosedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("TenantId", "PeriodYearMonth");

                    b.ToTable("petty_cash_periods", "nickfinance");
                });

            modelBuilder.Entity("NickERP.NickFinance.Core.Entities.Voucher", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ApproverUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoxId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("DisbursedAmount")
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("DisbursedAmountBase")
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTimeOffset?>("DisbursedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisbursedCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("DisbursedCurrencyBase")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("ReconciledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RejectedReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal>("RequestedAmount")
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("RequestedAmountBase")
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequestedCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("RequestedCurrencyBase")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<long>("SequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BoxId");

                    b.HasIndex("RequestedByUserId")
                        .HasDatabaseName("ix_petty_cash_vouchers_requester");

                    b.HasIndex("TenantId", "BoxId", "SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_petty_cash_vouchers_tenant_box_seq");

                    b.HasIndex("TenantId", "BoxId", "State")
                        .HasDatabaseName("ix_petty_cash_vouchers_tenant_box_state");

                    b.ToTable("petty_cash_vouchers", "nickfinance");
                });

            modelBuilder.Entity("NickERP.NickFinance.Core.Entities.Voucher", b =>
                {
                    b.HasOne("NickERP.NickFinance.Core.Entities.PettyCashBox", "Box")
                        .WithMany()
                        .HasForeignKey("BoxId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Box");
                });
#pragma warning restore 612, 618
        }
    }
}
