using NickERP.Platform.Tenancy.Entities;

namespace NickERP.Platform.Queueing.Entities;

/// <summary>
/// Abstract base for any unit of work that flows through the queueing
/// substrate. Each module subclasses this with a concrete <typeparamref name="TState"/>
/// (e.g. <c>InspectionWorkflowState</c>) and adds module-specific FK columns
/// (e.g. <c>CaseId</c>, <c>InvoiceId</c>). The base owns the cross-cutting
/// fields the platform cares about: identity, tenancy, current state,
/// optimistic-concurrency version, idempotency anchor, and timestamps.
/// </summary>
/// <remarks>
/// <para>
/// <b>Sole-writer discipline.</b> <see cref="CurrentState"/>'s setter is
/// <c>internal</c>. Only <c>WorkItemStateMachine&lt;TState,TTrigger&gt;</c>
/// (in the same assembly) can write it; controllers, workers, and consumers
/// in other assemblies cannot. This is the compile-time enforcement that
/// v1 lacked — v1 had 37 direct writers of <c>AnalysisGroup.Status</c>, of
/// which 34 bypassed the validator entirely. See plan
/// <c>i-need-an-analysis-abundant-pnueli.md</c> §B1 for the full inventory.
/// </para>
/// <para>
/// <b>Idempotency anchor.</b> Combined with the trigger and a timestamp,
/// produces a deterministic idempotency key for any queue row spawned by
/// a transition (see <see cref="NickERP.Platform.Audit.IdempotencyKey"/>).
/// Modules pick a stable anchor at intake — typically the upstream
/// scanner-event id, or a hash of <c>(scanner, scan_started_at)</c> — so
/// re-processing the same source twice doesn't double-emit.
/// </para>
/// <para>
/// <b>Versioning.</b> EF Core <c>[ConcurrencyCheck]</c> on
/// <see cref="Version"/> via Fluent API in the module's DbContext.
/// State machine transitions bump it; if two workers race the same
/// transition the loser's <c>SaveChangesAsync</c> throws
/// <c>DbUpdateConcurrencyException</c> and the queue claim is released.
/// </para>
/// </remarks>
/// <typeparam name="TState">
/// The state enum that the module's state machine operates on. Must be an
/// enum (struct constraint plus runtime check). Stored as the enum's
/// integer value in the DB.
/// </typeparam>
public abstract class WorkItem<TState> : ITenantOwned
    where TState : struct, Enum
{
    /// <summary>Stable primary key. Generated by the DB via <c>gen_random_uuid()</c> on insert.</summary>
    public Guid Id { get; set; }

    /// <inheritdoc />
    public long TenantId { get; set; }

    /// <summary>
    /// Discriminator naming the workflow definition this work item flows
    /// through (e.g. <c>"inspection"</c>, <c>"finance.invoice"</c>). Lets a
    /// future cross-module timeline view union work items from every
    /// module without losing context.
    /// </summary>
    public string Workflow { get; set; } = string.Empty;

    /// <summary>
    /// The state machine's current state for this work item. Setter is
    /// <c>internal</c> — only the state machine in this assembly may write
    /// it. Modules read it; they never assign it.
    /// </summary>
    public TState CurrentState { get; internal set; }

    /// <summary>
    /// Optimistic-concurrency token. Bumped by every state-machine
    /// transition. Configure with <c>e.Property(x =&gt; x.Version).IsConcurrencyToken()</c>
    /// in the owning DbContext.
    /// </summary>
    public int Version { get; set; }

    /// <summary>
    /// Stable identifier of the originating event — the input to
    /// idempotency-key construction for queue rows the state machine
    /// schedules. Pick something the upstream system also knows so a
    /// retry produces the same key.
    /// </summary>
    public string IdempotencyAnchor { get; set; } = string.Empty;

    /// <summary>UTC creation timestamp. Set by the DB default; immutable.</summary>
    public DateTimeOffset CreatedAt { get; set; }

    /// <summary>UTC last-update timestamp. Bumped by every state transition.</summary>
    public DateTimeOffset UpdatedAt { get; set; }

    /// <summary>
    /// Internal-only state-write hook used by
    /// <c>WorkItemStateMachine&lt;TState,TTrigger&gt;</c>. Application code
    /// never calls this directly — it goes through
    /// <c>TransitionAsync</c> which validates, audits, and saves
    /// atomically. Exposed as a method (rather than just relying on the
    /// internal setter) so derived classes can override to fire domain
    /// callbacks if they need to.
    /// </summary>
    internal virtual void SetState(TState newState)
    {
        CurrentState = newState;
    }
}
