using System.Security.Cryptography;
using System.Text;
using Microsoft.Extensions.Configuration;

namespace NickERP.Platform.Audit.Database;

/// <summary>
/// Sprint 13 / P2-FU-edge-auth — pure crypto for hashing per-edge-node
/// API keys. Lives in <c>Platform.Audit.Database</c> alongside the
/// <see cref="Entities.EdgeNodeApiKey"/> entity so both the
/// <c>NickERP.Inspection.Web</c> host (auth-time lookup) and the
/// <c>NickERP.Portal</c> host (issuance/revocation admin UI) can
/// consume it without a cross-project dependency.
///
/// <para>
/// <b>Hash construction.</b> Plaintext key bytes are HMAC-SHA256-ed
/// with a server-side hash key. The hash key is read from
/// <c>EdgeAuth:HashKey</c> config; if missing or empty, falls back
/// to a deterministic-per-host value derived through an
/// <see cref="EdgeKeyHashEnvelope"/> the host wires up. The split
/// keeps this class free of any ASP.NET / DataProtection dependency
/// — those concerns live in the host wiring.
/// </para>
///
/// <para>
/// <b>Plaintext storage.</b> The plaintext is generated once,
/// surfaced to the operator once, and discarded; the only persisted
/// trace is the HMAC hash + an 8-char non-secret prefix.
/// </para>
/// </summary>
public sealed class EdgeKeyHasher
{
    /// <summary>Configuration key for the explicit server-side hash key.</summary>
    public const string HashKeyConfigKey = "EdgeAuth:HashKey";

    /// <summary>Length (bytes) of CSPRNG plaintext keys generated by <see cref="GenerateApiKey"/>.</summary>
    public const int KeyMaterialLengthBytes = 32;

    /// <summary>Number of leading characters of the plaintext key surfaced as <see cref="Entities.EdgeNodeApiKey.KeyPrefix"/>.</summary>
    public const int KeyPrefixLength = 8;

    private readonly IConfiguration _config;
    private readonly IEdgeKeyHashEnvelope _envelope;

    public EdgeKeyHasher(IConfiguration config, IEdgeKeyHashEnvelope envelope)
    {
        _config = config ?? throw new ArgumentNullException(nameof(config));
        _envelope = envelope ?? throw new ArgumentNullException(nameof(envelope));
    }

    /// <summary>
    /// HMAC-SHA256 the plaintext under the server's hash key. The
    /// caller compares the returned bytes against
    /// <see cref="Entities.EdgeNodeApiKey.KeyHash"/> via
    /// <c>FixedTimeEquals</c>.
    /// </summary>
    public byte[] ComputeHash(string plaintextKey)
    {
        ArgumentException.ThrowIfNullOrEmpty(plaintextKey);
        var serverHashKey = ResolveServerHashKey();
        try
        {
            using var hmac = new HMACSHA256(serverHashKey);
            return hmac.ComputeHash(Encoding.UTF8.GetBytes(plaintextKey));
        }
        finally
        {
            CryptographicOperations.ZeroMemory(serverHashKey);
        }
    }

    /// <summary>
    /// Generate a fresh CSPRNG plaintext API key. URL-safe base64 (no
    /// padding) so the value pastes cleanly into appsettings without
    /// quoting hiccups around <c>=</c> / <c>+</c> / <c>/</c>.
    /// </summary>
    public static string GenerateApiKey()
    {
        var bytes = new byte[KeyMaterialLengthBytes];
        RandomNumberGenerator.Fill(bytes);
        return Convert.ToBase64String(bytes)
            .TrimEnd('=')
            .Replace('+', '-')
            .Replace('/', '_');
    }

    /// <summary>Compute the operator-visible 8-char prefix.</summary>
    public static string ComputePrefix(string plaintextKey)
    {
        ArgumentException.ThrowIfNullOrEmpty(plaintextKey);
        return plaintextKey.Length <= KeyPrefixLength
            ? plaintextKey
            : plaintextKey[..KeyPrefixLength];
    }

    private byte[] ResolveServerHashKey()
    {
        var configured = _config[HashKeyConfigKey];
        if (!string.IsNullOrEmpty(configured))
        {
            return Encoding.UTF8.GetBytes(configured);
        }
        return _envelope.DeriveFallbackHashKey();
    }
}

/// <summary>
/// Host-supplied envelope for deriving the fallback HMAC hash key when
/// <c>EdgeAuth:HashKey</c> is unset. Hosts inject an implementation
/// backed by <c>IDataProtectionProvider</c> (the production wiring in
/// the inspection + portal hosts); tests inject a deterministic
/// constant. Keeping this as an interface lets
/// <c>Platform.Audit.Database</c> stay free of an ASP.NET data-
/// protection dependency.
/// </summary>
public interface IEdgeKeyHashEnvelope
{
    /// <summary>
    /// Return a stable, host-scoped 32-byte hash key. Call sites must
    /// ensure the value is consistent across the host's lifetime —
    /// rotating the underlying secret would invalidate every issued
    /// API key.
    /// </summary>
    byte[] DeriveFallbackHashKey();
}
