using System.Globalization;
using System.Text;

namespace NickERP.Perf.Tests.Runner;

/// <summary>
/// Sprint 58 — markdown report writer. Replaces NBomber's
/// HTML/MD/TXT report bundle with a single per-scenario markdown file.
/// Format mirrors NBomber's table-per-scenario shape closely so existing
/// <c>docs/perf/baseline-2026-05-06.md</c> + downstream tooling stay
/// compatible with minimal edits.
/// </summary>
/// <remarks>
/// <para>
/// <b>Why markdown only.</b> The HTML report's value is the interactive
/// chart; we don't use that anywhere downstream. The .txt and .md were
/// near-duplicates. One markdown file per scenario is the minimum that
/// keeps the audit trail useful without burning effort on report shape.
/// </para>
/// </remarks>
public static class NickPerfReport
{
    /// <summary>
    /// Build the markdown report body. The runner writes this to
    /// <c>{reportFolder}/report.md</c>; downstream tooling reads it
    /// verbatim.
    /// </summary>
    public static string BuildMarkdown(string testName, string scenarioName, NickPerfStatsSnapshot snapshot)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(testName);
        ArgumentException.ThrowIfNullOrWhiteSpace(scenarioName);
        ArgumentNullException.ThrowIfNull(snapshot);

        var sb = new StringBuilder();
        sb.AppendLine($"# NickPerf report — {testName} / {scenarioName}");
        sb.AppendLine();
        sb.AppendLine($"**Generated (UTC):** {DateTime.UtcNow:u}");
        sb.AppendLine($"**Test:** {testName}");
        sb.AppendLine($"**Scenario:** {scenarioName}");
        sb.AppendLine();
        sb.AppendLine("## Summary");
        sb.AppendLine();
        sb.AppendLine("| Metric | Value |");
        sb.AppendLine("| --- | --- |");
        sb.AppendLine($"| Total | {snapshot.Total} |");
        sb.AppendLine($"| OK | {snapshot.ok} |");
        sb.AppendLine($"| Fail | {snapshot.fail} |");
        sb.AppendLine($"| Throughput (RPS) | {Format(snapshot.Rps)} |");
        sb.AppendLine($"| Elapsed | {snapshot.elapsed:c} |");
        sb.AppendLine();
        sb.AppendLine("## Latency (ms)");
        sb.AppendLine();
        sb.AppendLine("| Stat | Value |");
        sb.AppendLine("| --- | --- |");
        sb.AppendLine($"| min | {Format(snapshot.min)} |");
        sb.AppendLine($"| mean | {Format(snapshot.mean)} |");
        sb.AppendLine($"| max | {Format(snapshot.max)} |");
        sb.AppendLine($"| p50 | {Format(snapshot.p50)} |");
        sb.AppendLine($"| p75 | {Format(snapshot.p75)} |");
        sb.AppendLine($"| p95 | {Format(snapshot.p95)} |");
        sb.AppendLine($"| p99 | {Format(snapshot.p99)} |");
        sb.AppendLine();
        sb.AppendLine("---");
        sb.AppendLine();
        sb.AppendLine($"Generated by NickPerf in-tree runner (Sprint 58 — replaces NBomber 6.1.0).");
        return sb.ToString();
    }

    private static string Format(double v) => v.ToString("F2", CultureInfo.InvariantCulture);
}
