// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NickERP.Inspection.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NickERP.Inspection.Database.Migrations
{
    [DbContext(typeof(InspectionDbContext))]
    [Migration("20260505234450_Add_ScannerCursorSyncState")]
    partial class Add_ScannerCursorSyncState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("inspection")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.AnalysisService", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsBuiltInAllLocations")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ux_analysis_services_tenant_built_in")
                        .HasFilter("\"IsBuiltInAllLocations\" = TRUE");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_analysis_services_tenant_name");

                    b.ToTable("analysis_services", "inspection");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.AnalysisServiceLocation", b =>
                {
                    b.Property<Guid>("AnalysisServiceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("AnalysisServiceId", "LocationId");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_analysis_service_locations_location");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_analysis_service_locations_tenant");

                    b.ToTable("analysis_service_locations", "inspection");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.AnalysisServiceUser", b =>
                {
                    b.Property<Guid>("AnalysisServiceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("AssignedByUserId")
                        .HasColumnType("uuid");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("AnalysisServiceId", "UserId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_analysis_service_users_tenant");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_analysis_service_users_user");

                    b.ToTable("analysis_service_users", "inspection");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.AnalystReview", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Outcome")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("PeerDisagreementCount")
                        .HasColumnType("integer");

                    b.Property<string>("PostHocOutcomeJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("ReviewSessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReviewType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("RoiInteractionsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<Guid?>("StartedByUserId")
                        .HasColumnType("uuid");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<int>("TimeToDecisionMs")
                        .HasColumnType("integer");

                    b.Property<string>("VerdictChangesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.HasKey("Id");

                    b.HasIndex("ReviewSessionId");

                    b.HasIndex("TenantId", "ReviewType", "CreatedAt")
                        .HasDatabaseName("ix_analyst_reviews_tenant_type_time");

                    b.ToTable("analyst_reviews", "inspection");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.AuthorityDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ExternalSystemInstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("ExternalSystemInstanceId");

                    b.HasIndex("TenantId", "CaseId")
                        .HasDatabaseName("ix_authority_docs_tenant_case");

                    b.HasIndex("TenantId", "ReferenceNumber")
                        .HasDatabaseName("ix_authority_docs_tenant_ref");

                    b.ToTable("authority_documents", "inspection");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.CaseClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisServiceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ClaimedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("ClaimedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReleasedByUserId")
                        .HasColumnType("uuid");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisServiceId")
                        .HasDatabaseName("ix_case_claims_service");

                    b.HasIndex("CaseId")
                        .IsUnique()
                        .HasDatabaseName("ux_case_claims_active_per_case")
                        .HasFilter("\"ReleasedAt\" IS NULL");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_case_claims_tenant");

                    b.ToTable("case_claims", "inspection");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.CrossRecordDetection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetectedSubjectsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("DetectorVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("SplitCaseIdsJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CaseId", "DetectorVersion")
                        .IsUnique()
                        .HasDatabaseName("ux_cross_record_detection_case_version");

                    b.HasIndex("TenantId", "CaseId")
                        .HasDatabaseName("ix_cross_record_detection_tenant_case");

                    b.HasIndex("TenantId", "State", "DetectedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_cross_record_detection_tenant_state_detected");

                    b.ToTable("cross_record_detection", "inspection");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.ExternalSystemBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("ExternalSystemInstanceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("primary");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ExternalSystemInstanceId");

                    b.HasIndex("LocationId");

                    b.HasIndex("TenantId", "ExternalSystemInstanceId", "LocationId")
                        .IsUnique()
                        .HasDatabaseName("ux_external_bindings_tenant_inst_loc");

                    b.ToTable("external_system_bindings", "inspection");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.ExternalSystemInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("Scope")
                        .HasColumnType("integer");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_external_systems_tenant");

                    b.HasIndex("TypeCode")
                        .HasDatabaseName("ix_external_systems_type");

                    b.ToTable("external_system_instances", "inspection");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.Finding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalystReviewId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FindingType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("LocationInImageJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("info");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AnalystReviewId");

                    b.HasIndex("Severity")
                        .HasDatabaseName("ix_findings_severity");

                    b.HasIndex("TenantId", "FindingType")
                        .HasDatabaseName("ix_findings_tenant_type");

                    b.ToTable("findings", "inspection");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.IcumsSigningKey", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<byte[]>("KeyMaterialEncrypted")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset?>("RetiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("VerificationOnlyUntil")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "KeyId")
                        .IsUnique()
                        .HasDatabaseName("ux_icums_signing_keys_tenant_keyid");

                    b.HasIndex("TenantId", "ActivatedAt", "RetiredAt")
                        .HasDatabaseName("ix_icums_signing_keys_tenant_active");

                    b.ToTable("icums_signing_keys", "inspection");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.InspectionCase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedAnalystUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsSynthetic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("LegalHold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("LegalHoldAppliedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LegalHoldAppliedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LegalHoldReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("OpenedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("RetentionClass")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset?>("RetentionClassSetAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RetentionClassSetByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReviewQueue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StateEnteredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("StationId")
                        .HasColumnType("uuid");

                    b.Property<string>("SubjectIdentifier")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SubjectPayloadJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<int>("SubjectType")
                        .HasColumnType("integer");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AssignedAnalystUserId")
                        .HasDatabaseName("ix_cases_assigned_analyst");

                    b.HasIndex("LocationId");

                    b.HasIndex("StationId");

                    b.HasIndex("TenantId", "LegalHold")
                        .HasDatabaseName("ix_cases_legal_hold")
                        .HasFilter("\"LegalHold\" = TRUE");

                    b.HasIndex("TenantId", "SubjectIdentifier")
                        .HasDatabaseName("ix_cases_tenant_subject");

                    b.HasIndex("TenantId", "RetentionClass", "ClosedAt")
                        .HasDatabaseName("ix_cases_retention_class");

                    b.HasIndex("TenantId", "LocationId", "State", "OpenedAt")
                        .HasDatabaseName("ix_cases_tenant_loc_state_time");

                    b.HasIndex("TenantId", "ReviewQueue", "State", "OpenedAt")
                        .IsDescending(false, true, false, false)
                        .HasDatabaseName("ix_cases_tenant_queue_state_time");

                    b.ToTable("cases", "inspection");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_locations_tenant");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_locations_tenant_code");

                    b.ToTable("locations", "inspection");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.LocationAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("GrantedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdentityUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IdentityUserId")
                        .HasDatabaseName("ix_location_assignments_user");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_location_assignments_loc");

                    b.HasIndex("TenantId", "IdentityUserId", "LocationId")
                        .IsUnique()
                        .HasDatabaseName("ux_location_assignments_tenant_user_loc");

                    b.ToTable("location_assignments", "inspection");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.OutboundSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("ExternalSystemInstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResponseJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("pending");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("ExternalSystemInstanceId");

                    b.HasIndex("TenantId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_outbound_tenant_idempotency");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_outbound_tenant_status");

                    b.HasIndex("TenantId", "Status", "NextAttemptAt")
                        .HasDatabaseName("ix_outbound_tenant_status_next_attempt");

                    b.HasIndex("TenantId", "Status", "Priority", "SubmittedAt")
                        .IsDescending(false, false, true, false)
                        .HasDatabaseName("ix_outbound_tenant_status_priority_time");

                    b.ToTable("outbound_submissions", "inspection");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.OutcomePullCursor", b =>
                {
                    b.Property<Guid>("ExternalSystemInstanceId")
                        .HasColumnType("uuid");

                    b.Property<int>("ConsecutiveFailures")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset>("LastPullWindowUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastSuccessfulPullAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("ExternalSystemInstanceId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_outcome_pull_cursors_tenant");

                    b.ToTable("outcome_pull_cursors", "inspection");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.PostHocRolloutPhase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CurrentPhase")
                        .HasColumnType("integer");

                    b.Property<Guid>("ExternalSystemInstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("GateNotesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTimeOffset>("PhaseEnteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PromotedByUserId")
                        .HasColumnType("uuid");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("ExternalSystemInstanceId")
                        .HasDatabaseName("IX_posthoc_rollout_phase_ExternalSystemInstanceId");

                    b.HasIndex("TenantId", "ExternalSystemInstanceId")
                        .IsUnique()
                        .HasDatabaseName("ux_posthoc_rollout_tenant_instance");

                    b.ToTable("posthoc_rollout_phase", "inspection");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.ReviewSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalystUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("in-progress");

                    b.Property<DateTimeOffset>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AnalystUserId")
                        .HasDatabaseName("ix_review_sessions_analyst");

                    b.HasIndex("CaseId");

                    b.HasIndex("TenantId", "CaseId", "StartedAt")
                        .HasDatabaseName("ix_review_sessions_tenant_case_time");

                    b.ToTable("review_sessions", "inspection");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.RuleEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorityCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("EvaluatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("MutationsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("ProviderErrorsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<string>("ViolationsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CaseId", "AuthorityCode")
                        .IsUnique()
                        .HasDatabaseName("ux_rule_eval_tenant_case_authority");

                    b.HasIndex("TenantId", "CaseId", "EvaluatedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_rule_eval_tenant_case_at");

                    b.ToTable("rule_evaluations", "inspection");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.Scan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("OperatorUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ScannerDeviceInstanceId")
                        .HasColumnType("uuid");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("ScannerDeviceInstanceId")
                        .HasDatabaseName("ix_scans_device");

                    b.HasIndex("TenantId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_scans_tenant_idempotency");

                    b.HasIndex("TenantId", "CaseId", "CapturedAt")
                        .HasDatabaseName("ix_scans_tenant_case_time");

                    b.ToTable("scans", "inspection");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.ScanArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ArtifactKind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("Primary");

                    b.Property<int>("Channels")
                        .HasColumnType("integer");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("HeightPx")
                        .HasColumnType("integer");

                    b.Property<bool>("LegalHold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("LegalHoldAppliedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LegalHoldAppliedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LegalHoldReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ManifestJson")
                        .HasColumnType("jsonb");

                    b.Property<byte[]>("ManifestSha256")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("ManifestSignature")
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset?>("ManifestVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("RetentionClass")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset?>("RetentionClassSetAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RetentionClassSetByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ScanId")
                        .HasColumnType("uuid");

                    b.Property<string>("StorageUri")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<int>("WidthPx")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash")
                        .HasDatabaseName("ix_scan_artifacts_content_hash");

                    b.HasIndex("ScanId");

                    b.HasIndex("TenantId", "LegalHold")
                        .HasDatabaseName("ix_scan_artifacts_legal_hold")
                        .HasFilter("\"LegalHold\" = TRUE");

                    b.HasIndex("TenantId", "ManifestVerifiedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_scan_artifacts_tenant_manifest_verified");

                    b.HasIndex("TenantId", "ScanId")
                        .HasDatabaseName("ix_scan_artifacts_tenant_scan");

                    b.HasIndex("TenantId", "RetentionClass", "CreatedAt")
                        .HasDatabaseName("ix_scan_artifacts_retention_class");

                    b.ToTable("scan_artifacts", "inspection");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.ScanRenderArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("HeightPx")
                        .HasColumnType("integer");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("RenderedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("ScanArtifactId")
                        .HasColumnType("uuid");

                    b.Property<string>("StorageUri")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<int>("WidthPx")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ScanArtifactId", "Kind")
                        .IsUnique()
                        .HasDatabaseName("ux_render_artifact_kind");

                    b.HasIndex("TenantId", "ScanArtifactId")
                        .HasDatabaseName("ix_render_tenant_artifact");

                    b.ToTable("scan_render_artifacts", "inspection");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.ScanRenderAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("LastAttemptAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("PermanentlyFailedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ScanArtifactId")
                        .HasColumnType("uuid");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PermanentlyFailedAt")
                        .HasDatabaseName("ix_render_attempt_failed");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_render_attempt_tenant");

                    b.HasIndex("ScanArtifactId", "Kind")
                        .IsUnique()
                        .HasDatabaseName("ux_render_attempt_artifact_kind");

                    b.ToTable("scan_render_attempts", "inspection");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.ScannerCursorSyncState", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AdapterName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastAdvancedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastCursorValue")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ScannerDeviceTypeId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_cursor_sync_state_tenant");

                    b.HasIndex("TenantId", "ScannerDeviceTypeId", "AdapterName")
                        .IsUnique()
                        .HasDatabaseName("ux_cursor_sync_state_tenant_type_adapter");

                    b.ToTable("scanner_cursor_sync_states", "inspection");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.ScannerDeviceInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("StationId")
                        .HasColumnType("uuid");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("StationId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_scanners_tenant");

                    b.HasIndex("TypeCode")
                        .HasDatabaseName("ix_scanners_type");

                    b.HasIndex("TenantId", "LocationId")
                        .HasDatabaseName("ix_scanners_tenant_loc");

                    b.ToTable("scanner_device_instances", "inspection");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.ScannerOnboardingResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RecordedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScannerDeviceTypeId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_scanner_onboarding_tenant");

                    b.HasIndex("TenantId", "ScannerDeviceTypeId", "FieldName", "RecordedAt")
                        .IsDescending(false, false, false, true)
                        .HasDatabaseName("ix_scanner_onboarding_tenant_type_field_time");

                    b.ToTable("scanner_onboarding_responses", "inspection");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.ScannerThresholdProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset?>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProposalRationaleJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<int>("ProposedBy")
                        .HasColumnType("integer");

                    b.Property<Guid>("ScannerDeviceInstanceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ShadowCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ShadowOutcomeJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("ShadowStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ValuesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ScannerDeviceInstanceId")
                        .IsUnique()
                        .HasDatabaseName("ux_scanner_threshold_profiles_active")
                        .HasFilter("\"Status\" = 20");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_scanner_threshold_profiles_tenant");

                    b.HasIndex("TenantId", "ScannerDeviceInstanceId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ux_scanner_threshold_profiles_tenant_scanner_version");

                    b.ToTable("scanner_threshold_profiles", "inspection");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.SlaWindow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("BudgetMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("QueueTier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("QueueTierIsManual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<string>("WindowName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("CaseId", "WindowName")
                        .IsUnique()
                        .HasDatabaseName("ux_sla_window_open_per_case_window")
                        .HasFilter("\"ClosedAt\" IS NULL");

                    b.HasIndex("TenantId", "CaseId")
                        .HasDatabaseName("ix_sla_window_tenant_case");

                    b.HasIndex("TenantId", "QueueTier", "State")
                        .HasDatabaseName("ix_sla_window_tenant_tier_state");

                    b.HasIndex("TenantId", "State", "DueAt")
                        .HasDatabaseName("ix_sla_window_tenant_state_due");

                    b.ToTable("sla_window", "inspection");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.Station", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_stations_tenant");

                    b.HasIndex("TenantId", "LocationId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_stations_tenant_loc_code");

                    b.ToTable("stations", "inspection");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.ThresholdProfileHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ChangedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClassId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<double>("NewThreshold")
                        .HasColumnType("double precision");

                    b.Property<double?>("OldThreshold")
                        .HasColumnType("double precision");

                    b.Property<string>("Reason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("ScannerDeviceInstanceId")
                        .HasColumnType("uuid");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_threshold_history_tenant");

                    b.HasIndex("TenantId", "ScannerDeviceInstanceId", "ChangedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_threshold_history_tenant_scanner_time");

                    b.ToTable("threshold_profile_history", "inspection");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.Verdict", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Basis")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DecidedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("DecidedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Decision")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RevisedVerdictId")
                        .HasColumnType("uuid");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CaseId")
                        .IsUnique()
                        .HasDatabaseName("ux_verdicts_case");

                    b.HasIndex("TenantId", "Decision", "DecidedAt")
                        .HasDatabaseName("ix_verdicts_tenant_decision_time");

                    b.ToTable("verdicts", "inspection");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.WebhookCursor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AdapterName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("LastProcessedEventId")
                        .HasColumnType("uuid");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "AdapterName")
                        .IsUnique()
                        .HasDatabaseName("ux_webhook_cursors_tenant_adapter");

                    b.ToTable("webhook_cursors", "inspection");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.AnalysisServiceLocation", b =>
                {
                    b.HasOne("NickERP.Inspection.Core.Entities.AnalysisService", "AnalysisService")
                        .WithMany()
                        .HasForeignKey("AnalysisServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NickERP.Inspection.Core.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisService");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.AnalysisServiceUser", b =>
                {
                    b.HasOne("NickERP.Inspection.Core.Entities.AnalysisService", "AnalysisService")
                        .WithMany()
                        .HasForeignKey("AnalysisServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisService");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.AnalystReview", b =>
                {
                    b.HasOne("NickERP.Inspection.Core.Entities.ReviewSession", "Session")
                        .WithMany("Reviews")
                        .HasForeignKey("ReviewSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.AuthorityDocument", b =>
                {
                    b.HasOne("NickERP.Inspection.Core.Entities.InspectionCase", "Case")
                        .WithMany("Documents")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NickERP.Inspection.Core.Entities.ExternalSystemInstance", "ExternalSystemInstance")
                        .WithMany()
                        .HasForeignKey("ExternalSystemInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("ExternalSystemInstance");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.CaseClaim", b =>
                {
                    b.HasOne("NickERP.Inspection.Core.Entities.AnalysisService", "AnalysisService")
                        .WithMany()
                        .HasForeignKey("AnalysisServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NickERP.Inspection.Core.Entities.InspectionCase", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisService");

                    b.Navigation("Case");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.ExternalSystemBinding", b =>
                {
                    b.HasOne("NickERP.Inspection.Core.Entities.ExternalSystemInstance", "Instance")
                        .WithMany("Bindings")
                        .HasForeignKey("ExternalSystemInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NickERP.Inspection.Core.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Instance");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.Finding", b =>
                {
                    b.HasOne("NickERP.Inspection.Core.Entities.AnalystReview", "Review")
                        .WithMany("Findings")
                        .HasForeignKey("AnalystReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Review");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.InspectionCase", b =>
                {
                    b.HasOne("NickERP.Inspection.Core.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NickERP.Inspection.Core.Entities.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Location");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.LocationAssignment", b =>
                {
                    b.HasOne("NickERP.Inspection.Core.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.OutboundSubmission", b =>
                {
                    b.HasOne("NickERP.Inspection.Core.Entities.InspectionCase", "Case")
                        .WithMany("Submissions")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NickERP.Inspection.Core.Entities.ExternalSystemInstance", "ExternalSystemInstance")
                        .WithMany()
                        .HasForeignKey("ExternalSystemInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("ExternalSystemInstance");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.OutcomePullCursor", b =>
                {
                    b.HasOne("NickERP.Inspection.Core.Entities.ExternalSystemInstance", "ExternalSystemInstance")
                        .WithMany()
                        .HasForeignKey("ExternalSystemInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExternalSystemInstance");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.PostHocRolloutPhase", b =>
                {
                    b.HasOne("NickERP.Inspection.Core.Entities.ExternalSystemInstance", "ExternalSystemInstance")
                        .WithMany()
                        .HasForeignKey("ExternalSystemInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExternalSystemInstance");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.ReviewSession", b =>
                {
                    b.HasOne("NickERP.Inspection.Core.Entities.InspectionCase", "Case")
                        .WithMany("ReviewSessions")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.Scan", b =>
                {
                    b.HasOne("NickERP.Inspection.Core.Entities.InspectionCase", "Case")
                        .WithMany("Scans")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NickERP.Inspection.Core.Entities.ScannerDeviceInstance", "ScannerDeviceInstance")
                        .WithMany()
                        .HasForeignKey("ScannerDeviceInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("ScannerDeviceInstance");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.ScanArtifact", b =>
                {
                    b.HasOne("NickERP.Inspection.Core.Entities.Scan", "Scan")
                        .WithMany("Artifacts")
                        .HasForeignKey("ScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scan");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.ScanRenderArtifact", b =>
                {
                    b.HasOne("NickERP.Inspection.Core.Entities.ScanArtifact", "ScanArtifact")
                        .WithMany()
                        .HasForeignKey("ScanArtifactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanArtifact");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.ScannerDeviceInstance", b =>
                {
                    b.HasOne("NickERP.Inspection.Core.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NickERP.Inspection.Core.Entities.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Location");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.ScannerThresholdProfile", b =>
                {
                    b.HasOne("NickERP.Inspection.Core.Entities.ScannerDeviceInstance", "ScannerDeviceInstance")
                        .WithMany()
                        .HasForeignKey("ScannerDeviceInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ScannerDeviceInstance");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.Station", b =>
                {
                    b.HasOne("NickERP.Inspection.Core.Entities.Location", "Location")
                        .WithMany("Stations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.Verdict", b =>
                {
                    b.HasOne("NickERP.Inspection.Core.Entities.InspectionCase", "Case")
                        .WithOne("Verdict")
                        .HasForeignKey("NickERP.Inspection.Core.Entities.Verdict", "CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.AnalystReview", b =>
                {
                    b.Navigation("Findings");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.ExternalSystemInstance", b =>
                {
                    b.Navigation("Bindings");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.InspectionCase", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("ReviewSessions");

                    b.Navigation("Scans");

                    b.Navigation("Submissions");

                    b.Navigation("Verdict");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.Location", b =>
                {
                    b.Navigation("Stations");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.ReviewSession", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.Scan", b =>
                {
                    b.Navigation("Artifacts");
                });
#pragma warning restore 612, 618
        }
    }
}
