// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NickERP.Inspection.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NickERP.Inspection.Database.Migrations
{
    [DbContext(typeof(InspectionDbContext))]
    [Migration("20260427211653_Add_RLS_Policies")]
    partial class Add_RLS_Policies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("inspection")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.AnalystReview", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("PeerDisagreementCount")
                        .HasColumnType("integer");

                    b.Property<string>("PostHocOutcomeJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("ReviewSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("RoiInteractionsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<int>("TimeToDecisionMs")
                        .HasColumnType("integer");

                    b.Property<string>("VerdictChangesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.HasKey("Id");

                    b.HasIndex("ReviewSessionId");

                    b.ToTable("analyst_reviews", "inspection");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.AuthorityDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ExternalSystemInstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("ExternalSystemInstanceId");

                    b.HasIndex("TenantId", "CaseId")
                        .HasDatabaseName("ix_authority_docs_tenant_case");

                    b.HasIndex("TenantId", "ReferenceNumber")
                        .HasDatabaseName("ix_authority_docs_tenant_ref");

                    b.ToTable("authority_documents", "inspection");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.ExternalSystemBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("ExternalSystemInstanceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("primary");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ExternalSystemInstanceId");

                    b.HasIndex("LocationId");

                    b.HasIndex("TenantId", "ExternalSystemInstanceId", "LocationId")
                        .IsUnique()
                        .HasDatabaseName("ux_external_bindings_tenant_inst_loc");

                    b.ToTable("external_system_bindings", "inspection");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.ExternalSystemInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("Scope")
                        .HasColumnType("integer");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_external_systems_tenant");

                    b.HasIndex("TypeCode")
                        .HasDatabaseName("ix_external_systems_type");

                    b.ToTable("external_system_instances", "inspection");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.Finding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalystReviewId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FindingType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("LocationInImageJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("info");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AnalystReviewId");

                    b.HasIndex("Severity")
                        .HasDatabaseName("ix_findings_severity");

                    b.HasIndex("TenantId", "FindingType")
                        .HasDatabaseName("ix_findings_tenant_type");

                    b.ToTable("findings", "inspection");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.InspectionCase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedAnalystUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("OpenedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StateEnteredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("StationId")
                        .HasColumnType("uuid");

                    b.Property<string>("SubjectIdentifier")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SubjectPayloadJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<int>("SubjectType")
                        .HasColumnType("integer");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AssignedAnalystUserId")
                        .HasDatabaseName("ix_cases_assigned_analyst");

                    b.HasIndex("LocationId");

                    b.HasIndex("StationId");

                    b.HasIndex("TenantId", "SubjectIdentifier")
                        .HasDatabaseName("ix_cases_tenant_subject");

                    b.HasIndex("TenantId", "LocationId", "State", "OpenedAt")
                        .HasDatabaseName("ix_cases_tenant_loc_state_time");

                    b.ToTable("cases", "inspection");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_locations_tenant");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_locations_tenant_code");

                    b.ToTable("locations", "inspection");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.LocationAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("GrantedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdentityUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IdentityUserId")
                        .HasDatabaseName("ix_location_assignments_user");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_location_assignments_loc");

                    b.HasIndex("TenantId", "IdentityUserId", "LocationId")
                        .IsUnique()
                        .HasDatabaseName("ux_location_assignments_tenant_user_loc");

                    b.ToTable("location_assignments", "inspection");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.OutboundSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("ExternalSystemInstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTimeOffset?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResponseJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("pending");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("ExternalSystemInstanceId");

                    b.HasIndex("TenantId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_outbound_tenant_idempotency");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_outbound_tenant_status");

                    b.ToTable("outbound_submissions", "inspection");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.ReviewSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalystUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("in-progress");

                    b.Property<DateTimeOffset>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AnalystUserId")
                        .HasDatabaseName("ix_review_sessions_analyst");

                    b.HasIndex("CaseId");

                    b.HasIndex("TenantId", "CaseId", "StartedAt")
                        .HasDatabaseName("ix_review_sessions_tenant_case_time");

                    b.ToTable("review_sessions", "inspection");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.Scan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("OperatorUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ScannerDeviceInstanceId")
                        .HasColumnType("uuid");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("ScannerDeviceInstanceId")
                        .HasDatabaseName("ix_scans_device");

                    b.HasIndex("TenantId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_scans_tenant_idempotency");

                    b.HasIndex("TenantId", "CaseId", "CapturedAt")
                        .HasDatabaseName("ix_scans_tenant_case_time");

                    b.ToTable("scans", "inspection");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.ScanArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ArtifactKind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("Primary");

                    b.Property<int>("Channels")
                        .HasColumnType("integer");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("HeightPx")
                        .HasColumnType("integer");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ScanId")
                        .HasColumnType("uuid");

                    b.Property<string>("StorageUri")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<int>("WidthPx")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash")
                        .HasDatabaseName("ix_scan_artifacts_content_hash");

                    b.HasIndex("ScanId");

                    b.HasIndex("TenantId", "ScanId")
                        .HasDatabaseName("ix_scan_artifacts_tenant_scan");

                    b.ToTable("scan_artifacts", "inspection");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.ScanRenderArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("HeightPx")
                        .HasColumnType("integer");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("RenderedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("ScanArtifactId")
                        .HasColumnType("uuid");

                    b.Property<string>("StorageUri")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<int>("WidthPx")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ScanArtifactId", "Kind")
                        .IsUnique()
                        .HasDatabaseName("ux_render_artifact_kind");

                    b.HasIndex("TenantId", "ScanArtifactId")
                        .HasDatabaseName("ix_render_tenant_artifact");

                    b.ToTable("scan_render_artifacts", "inspection");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.ScannerDeviceInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("StationId")
                        .HasColumnType("uuid");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("StationId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_scanners_tenant");

                    b.HasIndex("TypeCode")
                        .HasDatabaseName("ix_scanners_type");

                    b.HasIndex("TenantId", "LocationId")
                        .HasDatabaseName("ix_scanners_tenant_loc");

                    b.ToTable("scanner_device_instances", "inspection");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.Station", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_stations_tenant");

                    b.HasIndex("TenantId", "LocationId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_stations_tenant_loc_code");

                    b.ToTable("stations", "inspection");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.Verdict", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Basis")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DecidedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("DecidedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Decision")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RevisedVerdictId")
                        .HasColumnType("uuid");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CaseId")
                        .IsUnique()
                        .HasDatabaseName("ux_verdicts_case");

                    b.HasIndex("TenantId", "Decision", "DecidedAt")
                        .HasDatabaseName("ix_verdicts_tenant_decision_time");

                    b.ToTable("verdicts", "inspection");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.AnalystReview", b =>
                {
                    b.HasOne("NickERP.Inspection.Core.Entities.ReviewSession", "Session")
                        .WithMany("Reviews")
                        .HasForeignKey("ReviewSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.AuthorityDocument", b =>
                {
                    b.HasOne("NickERP.Inspection.Core.Entities.InspectionCase", "Case")
                        .WithMany("Documents")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NickERP.Inspection.Core.Entities.ExternalSystemInstance", "ExternalSystemInstance")
                        .WithMany()
                        .HasForeignKey("ExternalSystemInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("ExternalSystemInstance");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.ExternalSystemBinding", b =>
                {
                    b.HasOne("NickERP.Inspection.Core.Entities.ExternalSystemInstance", "Instance")
                        .WithMany("Bindings")
                        .HasForeignKey("ExternalSystemInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NickERP.Inspection.Core.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Instance");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.Finding", b =>
                {
                    b.HasOne("NickERP.Inspection.Core.Entities.AnalystReview", "Review")
                        .WithMany("Findings")
                        .HasForeignKey("AnalystReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Review");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.InspectionCase", b =>
                {
                    b.HasOne("NickERP.Inspection.Core.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NickERP.Inspection.Core.Entities.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Location");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.LocationAssignment", b =>
                {
                    b.HasOne("NickERP.Inspection.Core.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.OutboundSubmission", b =>
                {
                    b.HasOne("NickERP.Inspection.Core.Entities.InspectionCase", "Case")
                        .WithMany("Submissions")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NickERP.Inspection.Core.Entities.ExternalSystemInstance", "ExternalSystemInstance")
                        .WithMany()
                        .HasForeignKey("ExternalSystemInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("ExternalSystemInstance");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.ReviewSession", b =>
                {
                    b.HasOne("NickERP.Inspection.Core.Entities.InspectionCase", "Case")
                        .WithMany("ReviewSessions")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.Scan", b =>
                {
                    b.HasOne("NickERP.Inspection.Core.Entities.InspectionCase", "Case")
                        .WithMany("Scans")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NickERP.Inspection.Core.Entities.ScannerDeviceInstance", "ScannerDeviceInstance")
                        .WithMany()
                        .HasForeignKey("ScannerDeviceInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("ScannerDeviceInstance");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.ScanArtifact", b =>
                {
                    b.HasOne("NickERP.Inspection.Core.Entities.Scan", "Scan")
                        .WithMany("Artifacts")
                        .HasForeignKey("ScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scan");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.ScanRenderArtifact", b =>
                {
                    b.HasOne("NickERP.Inspection.Core.Entities.ScanArtifact", "ScanArtifact")
                        .WithMany()
                        .HasForeignKey("ScanArtifactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanArtifact");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.ScannerDeviceInstance", b =>
                {
                    b.HasOne("NickERP.Inspection.Core.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NickERP.Inspection.Core.Entities.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Location");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.Station", b =>
                {
                    b.HasOne("NickERP.Inspection.Core.Entities.Location", "Location")
                        .WithMany("Stations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.Verdict", b =>
                {
                    b.HasOne("NickERP.Inspection.Core.Entities.InspectionCase", "Case")
                        .WithOne("Verdict")
                        .HasForeignKey("NickERP.Inspection.Core.Entities.Verdict", "CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.AnalystReview", b =>
                {
                    b.Navigation("Findings");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.ExternalSystemInstance", b =>
                {
                    b.Navigation("Bindings");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.InspectionCase", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("ReviewSessions");

                    b.Navigation("Scans");

                    b.Navigation("Submissions");

                    b.Navigation("Verdict");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.Location", b =>
                {
                    b.Navigation("Stations");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.ReviewSession", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("NickERP.Inspection.Core.Entities.Scan", b =>
                {
                    b.Navigation("Artifacts");
                });
#pragma warning restore 612, 618
        }
    }
}
